  steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  
 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
  
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/continual-block-339821/cloud-spanner-build', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/continual-block-339821/cloud-spanner-build']
